# 인공지능 입문 2강 실습 : Colab 사용법, 그리고 Numpy 배열과 연산

**기본 파이썬 프로그래밍 및 Colab의 주요 기능들에서 잘 숙지하도록 하자.**
        
        - 파일 불러오기, 저장, 다운로드, 런타임 설정(GPU 할당), 텍스트 셀의 목차 기능, 드라이브 마운트, 주석처리 기능 등

In [27]:
'''
import를 통해 라이브러리 불러온다.
as를 통해서 import로 불러온 라이브러리명을 재지정한다.
위 예시에서는 numpy를 np로 재지정한 것.
'''
import numpy as np

- Numpy 라이브러리는 머신러닝 관련 코드에서 많이 사용 되는(배열에 대한 다양한 수학 연산이 가능) 라이브러리이다.
- 아래 사이트는 Numpy 공식 도큐먼트 사이트로 Numpy에 대해서 더 알고 싶다면 해당 사이트를 방문하여 확인할 수 있다.

    [Numpy 공식 도큐먼트 사이트](https://numpy.org/doc/stable/user/absolute_beginners.html)
- 참고: 라이브러리란?
        - 라이브러리 : 여러 패키지와 모듈을 모아놓은 것
        - 패키지 : 특정 기능과 관련된 여러 모듈이 모여있는 한 폴더
        - 모듈 : 여러가지 함수, 변수 등을 모아 놓은 것

- "print_obj"는 출력하려는 객체(object) "이름"과 객체가 실제 저장하는 내용(값)을 출력하는 역할을 한다.
    - cf. escape 이스케이프 코드 : \n - 문자열 안에서 줄을 바꿀 때 사용
    - cf. 포맷팅(Formatting) : 문자열안에 특정부분을 특정 변수의 위치로 정해줌으로써 해당 변수의 값에 따라 문자열 자체가 변경 될 수 있게 하는 기능
        - 3가지 방법 : % 포맷팅, format 포맷팅, printf()
        - (문자열 포맷 코드) %s : 문자열(String)

In [28]:
def print_obj(obj, name):  # 변수와 변수의 이름을 입력하면 출력해주는 함수 정의.
    print("%s:\n%s\n" % (name, obj))  # %s -> name, %s -> obj, \n -> 개행

### 스칼라(Scalars), 벡터(Vectors), 행렬(Matrices)

In [29]:
# 1과 1. 의 차이점 : 1은 정수를 의미하고 1.은 실수를 의미한다.
array0 = np.array(1.) # 0차원 배열, 스칼라
array1 = np.array([1., 2., 3.]) # 1차원 배열, 벡터
array2 = np.array([[1., 2., 3.], [4., 5., 6.]]) # 2차원 배열, 행렬

In [30]:
# 앞서 정의한 print_obj 함수를 활용하자.
print_obj(array0, "스칼라")
print_obj(array1, "벡터")
print_obj(array2, "행렬")

스칼라:
1.0

벡터:
[1. 2. 3.]

행렬:
[[1. 2. 3.]
 [4. 5. 6.]]



- "array.ndim"은 배열의 차원의 수를 알려주는 기능을 한다.
- 1차원 배열, 2차원 배열을 추가로 학습하면 ndim의 기능이 이해가 쉽다.

In [31]:
print_obj(array0.ndim, "스칼라의 차원")  # ndim -> 차원의 크기를 반환
print_obj(array1.ndim, "벡터의 차원")
print_obj(array2.ndim, "행렬의 차원")

스칼라의 차원:
0

벡터의 차원:
1

행렬의 차원:
2



- shape는 배열의 모양(각 차원에 존재하는 요소(값)의 수를 의미)을 알려준다.
- array2와 array4는 어떤 차이점이 있을까?
    - np.array([1,2,3])는 행의 갯수 3만 반환하지만,np.array([[1,2,3]])는 1개의 행과 3개의 열로 구성된 행렬의 모양을 반환한다.  

In [32]:
print_obj(array0.shape, "array0의 shape")  # shape -> array의 형태 혹은 모양을 의미. 각 차원의 수와 성분의 수로 구성.
print_obj(array1.shape, "array1의 shape")
print_obj(array2.shape, "array2의 shape")

array3 = np.array([[1,2,3]])
print_obj(array3.shape, "array3의 shape")

array0의 shape:
()

array1의 shape:
(3,)

array2의 shape:
(2, 3)

array3의 shape:
(1, 3)



### 텐서(Tensors) (N-dimensional array)

- 스칼라 값은 0차원 텐서, 벡터는 1차원 텐서, 행렬은 2차원 텐서, 행렬의 배열은 3차원 텐서, 3차원 텐서의 배열(행렬의 배열의 배열)은 4차원 텐서이다.
- N차원 텐서란 무엇인지 알아보자.

In [33]:
tensor1 = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
tensor2 = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])

In [34]:
print_obj(tensor1, "tensor1")
print_obj(tensor1.ndim, "tensor1.ndim")
print_obj(tensor1.shape, "tensor1.shape")

print_obj(tensor2, "tensor2")
print_obj(tensor2.ndim, "tensor2.ndim")
print_obj(tensor2.shape, "tensor2.shape")

tensor1:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

tensor1.ndim:
3

tensor1.shape:
(2, 2, 3)

tensor2:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

tensor2.ndim:
4

tensor2.shape:
(2, 2, 2, 3)



### 넘파이 배열 정의 (Defining Numpy arrays)

In [35]:
'''
1을 성분으로 하는 배열을 생성한다.
파라미터에 입력한 크기 만큼의 배열이 생성된다.
'''
ones = np.ones(10)
print_obj(ones, "np.ones(10)")

np.ones(10):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]



In [36]:
'''
0을 성분으로 하는 배열을 생성한다.
파라미터에 입력한 크기 만큼의 배열이 생성된다.
'''
zeros = np.zeros((2, 5))
print_obj(zeros, "np.zeros((2, 5))")

np.zeros((2, 5)):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]



In [37]:
'''
파라미터에 배열의 크기와 값을 입력한다.
입력된 크기만큼의 배열을 만들고 입력한 값으로 배열을 채운다.
'''
full = np.full((2,5), 5)
print_obj(full, "np.full((2,5), 5)")

full2 = np.full((1,1,1), -1)
print_obj(full2, "np.full((1,1,1), -1)")

np.full((2,5), 5):
[[5 5 5 5 5]
 [5 5 5 5 5]]

np.full((1,1,1), -1):
[[[-1]]]



In [38]:
'''
파라미터에 입력된 크기 만큼의 배열을 생성한다.
만들어진 배열에 랜덤한 값으로 값을 채워준다.
입력되는 값은 0~1 사이의 실수로 소숫점 8째 자리까지 보인다.
'''
random = np.random.random((2, 3, 4))
print_obj(random, "np.random.random((2, 3, 4))")

np.random.random((2, 3, 4)):
[[[0.77523832 0.77767867 0.92797329 0.52448693]
  [0.7549115  0.75415252 0.61896005 0.19362576]
  [0.75918926 0.56778424 0.37682148 0.9385796 ]]

 [[0.70175314 0.06670689 0.29630871 0.10817918]
  [0.96296323 0.24031736 0.69584492 0.96526498]
  [0.36010759 0.84690692 0.6972837  0.40899331]]]



In [39]:
'''
파라미터로 입력된 크기 만큼의 배열을 생성한다.
0부터 1씩 증가시켜가며 입력 크기 만큼 값을 채운다.
예) 등차수열
'''
arange = np.arange(10)
print_obj(arange, "np.arange(10)")

np.arange(10):
[0 1 2 3 4 5 6 7 8 9]



In [40]:
'''
변수의 자료형을 변경하고 싶을 때 사용하는 함수이다.
arange를 통해서 만들어진 배열의 내부 값은 int(정수)형인데, 다음과 같이 float(실수)형으로 변경이 가능하다.
'''
astype = np.arange(10).astype(float)
print_obj(astype, "np.arange(10).astype(float)")

np.arange(10).astype(float):
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]



In [41]:
'''
이미 모양이 결정되어 있는 배열의 모양을 재설정하는 함수이다.
단, 새로운 모양이 배열에서 실제로 변경 가능한 모양이어야 한다.
'''
reshape = np.arange(10).reshape((5,2))
print_obj(reshape, "np.arange(10).reshape((5,2)")

np.arange(10).reshape((5,2):
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]



### 인덱스 (Indexing) & 슬라이싱 (Slicing)

**인덱싱**
- 행렬의 인덱싱을 이해하기 위해서는 인덱스 번호와 저장 순서의 차이를 알아야한다.
    - [a, b, c, d]의 4개의 값이 들어있는 리스트의 첫번째 저장요소는 a, 두 번째 저장요소는 b, 세번째 저장요소는 c이다.
    -  인덱스를 사용할 때 첫번째 저장요소의 인덱스는 0, 두번째 저장요소의 인덱스는 1, i번째 저장요소의 인덱스는 i-1이다.

**슬라이싱**
- ":"연산자를 이용한 인덱싱을 슬라이싱이라고 한다.
- 슬라이싱 기호의 시작 인덱스와 종료 인덱스는 생략이 가능하다.
    1.  ":"기호 앞에 시작 인덱스를 생략하면 자동으로 시작 인덱스인 0으로 간주
    2.   ":" 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
    3.   ":" 기호 앞 뒤를 모두 생략하면 시작부터 끝

**스텝의 부여**

- 슬라이싱에서 ":"기호가 2개 사용되는 경우는 인덱스에 스텝을 부여하는 경우이다. "a[0:10:2]"와 "a[2:6:3]"의 동작 결과를 통해 스텝의 동작을 추정해보자.
- 결과적으로는 "시작인덱스:종료값:스텝"으로 명령이 전달됨을 알 수 있다. 스텝을 부여할 때는 "음의 간격"을 부여할 수도 있다.

In [42]:
'''
인덱스는 목차, 순서, 색인 등을 의미, 즉 몇번째인지 순서를 의미한다.
배열에 있는 데이터를 인덱스를 통해서 접근이 가능하다.
일반적으로 0이상의 인덱스는 앞에서부터의 접근이고, 0이하의 인덱스는 뒤에서부터의 접근이다.
'''
array_index = np.arange(10)
print_obj(array_index, "np.arange(10)")
print_obj(array_index[0], "array_index[0]")
print_obj(array_index[1], "array_index[1]")
print_obj(array_index[-1], "array_index[-1]")
print_obj(array_index[-3], "array_index[-3]")

'''
콜론(:)을 통해서 범위 형태의 인덱스를 지정할 수 있다.
일반적으로 콜론 앞 뒤의 인덱스 범위 내의 데이터 전체에 접근한다.
'''
print_obj(array_index[0:10], "array_index[0:10]")
print_obj(array_index[0:], "array_index[0:]")
print_obj(array_index[:],"array_index[:]")
print_obj(array_index[:10], "array_index[:10]")
print_obj(array_index[7:], "array_index[7:]")
print_obj(array_index[:5], "array_index[:5]")
print_obj(array_index[2:5], "array_index[2:5]")

'''
콜론(:)이 하나의 인덱스에 두개가 사용된다면, 마지막 콜론 뒤의 숫자는 스텝을 의미한다.
스텝은 인덱싱 범위 내에서 얼만큼 건너뛰며 데이터에 접근할 것인지를 의미한다.
'''
print_obj(array_index[0:10:2], "array_index[0:10:2]")
print_obj(array_index[0:10:3], "array_index[0:10:3]")
print_obj(array_index[2:6:3], "array_index[2:6:3]")
print_obj(array_index[::-1], "array_index[::-1]")
print_obj(array_index[8:5:-1], "array_index[8:5:-1]")
print_obj(array_index[8:5], "array_index[8:5]")

np.arange(10):
[0 1 2 3 4 5 6 7 8 9]

array_index[0]:
0

array_index[1]:
1

array_index[-1]:
9

array_index[-3]:
7

array_index[0:10]:
[0 1 2 3 4 5 6 7 8 9]

array_index[0:]:
[0 1 2 3 4 5 6 7 8 9]

array_index[:]:
[0 1 2 3 4 5 6 7 8 9]

array_index[:10]:
[0 1 2 3 4 5 6 7 8 9]

array_index[7:]:
[7 8 9]

array_index[:5]:
[0 1 2 3 4]

array_index[2:5]:
[2 3 4]

array_index[0:10:2]:
[0 2 4 6 8]

array_index[0:10:3]:
[0 3 6 9]

array_index[2:6:3]:
[2 5]

array_index[::-1]:
[9 8 7 6 5 4 3 2 1 0]

array_index[8:5:-1]:
[8 7 6]

array_index[8:5]:
[]



In [43]:
'''
2차원이상의 인덱스도 동일한 방법으로 접근이 가능하다.
하나의 인덱스에 ,를 활용해서 표현할 수도 있고 다수의 인덱스를 활용할 수 있다.
'''
array_index = np.arange(9).reshape((3,3))
print_obj(array_index, "array_index")
print_obj(array_index[0][0], "array_index[0][0]")
print_obj(array_index[0,0], "array_index[0,0]")
print_obj(array_index[1,1], "array_index[1,1]")

array_index = np.arange(4*3*2).reshape((4, 3, 2))
print_obj(array_index, "array_index")
print_obj(array_index[2, 1, 0], "array_index[2, 1, 0]")

array_index:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

array_index[0][0]:
0

array_index[0,0]:
0

array_index[1,1]:
4

array_index:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

array_index[2, 1, 0]:
14



In [44]:
'''
슬라이싱을 잘 활용하면 하나의 행 혹은 열 단위로 행렬 형태의 데이터에 접근 가능하다.
'''
array_index = np.arange(24).reshape((6,4))
print_obj(array_index, "array_index")
print_obj(array_index[:,[0, 2, 3]], "array_index[idx]")
print_obj(array_index[[0, 2, 3], :], "array_index[idx]")

array_index:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

array_index[idx]:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

array_index[idx]:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]



### 수학적 연산 (Math Operations)

- 행렬의 곱은 NXM의 행렬과 MXK의 행렬을 곱하면 NXK의 행렬이 산출된다.
- 3X2 행렬과 3X2 행렬을 곱하는데, 이것은 2장에서 배운 행렬곱과 맞지 않는다.
- "*"기호와 "/"기호를 사용하면 동일한 크기의 행렬에 대하여 A[i,j]와 B[i,j]에 대하여 원소별로 곱하기를 하거나 나누기를 한 결과를 얻게 된다
- 2장에서 배운 행렬의 곱은 numpy의 matmul함수를 이용하거나 "@"연산자로 표현한다.

In [45]:
'''
기본 사칙 연산
'''
mat1 = np.arange(6).reshape((3,2))
mat2 = np.ones((3, 2))
print_obj(mat1, "mat1")
print_obj(mat2, "mat2")
print_obj(mat1+mat2, "mat1+mat2")
print_obj(mat1-mat2, "mat1-mat2")
print_obj(mat1*mat2, "mat1*mat2")
print_obj(mat1/mat2, "mat1/mat2")

mat1:
[[0 1]
 [2 3]
 [4 5]]

mat2:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

mat1+mat2:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

mat1-mat2:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

mat1*mat2:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

mat1/mat2:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



In [46]:
'''
Unary 연산
'''
mat = np.arange(6).reshape((3,2))
print_obj(mat, "mat")
print_obj(mat.sum(), "mat.sum()")
print_obj(mat.sum(axis=0), "mat.sum(axis=0)")  # axis는 축을 의미
print_obj(mat.sum(axis=1), "mat.sum(axis=1)")
print_obj(mat.mean(), "mat.mean()")
print_obj(mat.max(), "mat.max()")
print_obj(mat.min(), "mat.min()")

mat:
[[0 1]
 [2 3]
 [4 5]]

mat.sum():
15

mat.sum(axis=0):
[6 9]

mat.sum(axis=1):
[1 5 9]

mat.mean():
2.5

mat.max():
5

mat.min():
0



In [47]:
'''
벡터의 내적 연산
'''
mat1 = np.arange(3).astype('float')
mat2 = np.ones(3)
print_obj(mat1, "mat1")
print_obj(mat2, "mat2")
print_obj(np.dot(mat1, mat2), "mat1 dot mat2")

mat1:
[0. 1. 2.]

mat2:
[1. 1. 1.]

mat1 dot mat2:
3.0



In [48]:
'''
행렬의 곱연산
'''
mat1 = np.arange(6).reshape((3, 2))
mat2 = np.ones((2, 3))
print_obj(mat1, "mat1")
print_obj(mat2, "mat2")
print_obj(np.dot(mat1,mat2), "mat1 dot mat2")
print_obj(mat1@mat2, "mat1 @ mat2")
print_obj(np.matmul(mat1,mat2), "matmul(mat1,mat2)")

mat3 = np.arange(24).reshape((4, 3, 2))
mat4 = np.ones((4, 2, 3))
print_obj(mat3, "mat3")
print_obj(mat4, "mat4")
print_obj(np.dot(mat3,mat4).shape, "mat3 dot mat4")
print_obj((mat3@mat4).shape, "mat3 @ mat4")
print_obj(np.matmul(mat3,mat4).shape, "matmul(mat3,mat4)")

mat1:
[[0 1]
 [2 3]
 [4 5]]

mat2:
[[1. 1. 1.]
 [1. 1. 1.]]

mat1 dot mat2:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

mat1 @ mat2:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

matmul(mat1,mat2):
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

mat3:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

mat4:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

mat3 dot mat4:
(4, 3, 4, 3)

mat3 @ mat4:
(4, 3, 3)

matmul(mat3,mat4):
(4, 3, 3)



### 형태 변형 (Shape Manipulation)

- reshape()함수의 인자로 "-1"이 주어진 경우 최초 자료형의 원소의 갯수와 -1이 아닌 인자의 값을 이용하여 "-1"로 할당된 차원의 정확한 값이 추정된다.
- reshape(6, -1)와 reshape(-1,6)의 출력 결과를 확인하여 보자.

In [49]:
'''
-1을 활용하여 reshape 형태 변형에 사용한다.
'''
array1 = np.arange(24).reshape((2, 3, 4))
print_obj(array1, "np.arange(24).reshape((2, 3, 4))")
array2 = array1.reshape((6, 4))
print_obj(array2, "array1.reshape((6, 4))")
array3 = array1.reshape((6, -1))
print_obj(array3, "array1.reshape((6, -1))")

np.arange(24).reshape((2, 3, 4)):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

array1.reshape((6, 4)):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

array1.reshape((6, -1)):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [50]:
'''
기존 배열보다 더 큰 차원으로 확대하는것도 가능하다.
'''
array = np.arange(3)
print_obj(array, "array")
print_obj(array[:, None], "array[:, None]")

array:
[0 1 2]

array[:, None]:
[[0]
 [1]
 [2]]



In [51]:
'''
스택과 concatenation 모두 두개의 배열을 연결하는 기능을 한다.
스택의 h는 horizontal을 의미하고 v는 vertical을 의미한다.
'''
array1 = np.ones((3,2))
array2 = np.zeros((3,2))
print_obj(array1, "array1")
print_obj(array2, "array2")

print_obj(np.vstack([array1, array2]), "array1+2 vstack")
print_obj(np.hstack([array1, array2]), "array1+2 hstack")
print_obj(np.hstack([array1, array2, array1]), "array1+2+1 hstack")

print_obj(np.concatenate([array1, array2], axis=0), "array1+2 concat axis=0")
print_obj(np.concatenate([array1, array2], axis=1), "array1+2 concat axis=1")

array1:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

array2:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

array1+2 vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

array1+2 hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

array1+2+1 hstack:
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]

array1+2 concat axis=0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

array1+2 concat axis=1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]



In [52]:
'''
전치행렬
'''
array = np.arange(6).reshape((3, 2))
print_obj(array, "array")
print_obj(array.T, "array.T")

array1 = np.arange(24).reshape((4, 3, 2))
print_obj(array1, "array1")
array2 = np.transpose(array1, [0, 2, 1])
print_obj(array2, "Swap axis 1 and 2")
print_obj(array2.shape, "Swapped shape")
array3 = np.transpose(array1, [1, 0, 2])
print_obj(array3, "Swap axis 0 and 1")
print_obj(array3.shape, "Swapped shape")

array:
[[0 1]
 [2 3]
 [4 5]]

array.T:
[[0 2 4]
 [1 3 5]]

array1:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

Swap axis 1 and 2:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

Swapped shape:
(4, 2, 3)

Swap axis 0 and 1:
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]

Swapped shape:
(3, 4, 2)



$6\times 4$ 차원의 행렬을 전치 연산하면 $4\times 6$ 차원의 행렬이 된다.

$$
\begin{align}
X =
\begin{bmatrix}
\boxed{\begin{matrix} x_{1, 1} & x_{1, 2} & x_{1, 3} & x_{1, 4}\end{matrix}}  \\
\begin{matrix} x_{2, 1} & x_{2, 2} & x_{2, 3} & x_{2, 4}\end{matrix} \\
\begin{matrix} x_{3, 1} & x_{3, 2} & x_{3, 3} & x_{3, 4}\end{matrix} \\
\begin{matrix} x_{4, 1} & x_{4, 2} & x_{4, 3} & x_{4, 4}\end{matrix} \\
\begin{matrix} x_{5, 1} & x_{5, 2} & x_{5, 3} & x_{5, 4}\end{matrix} \\
\begin{matrix} x_{6, 1} & x_{6, 2} & x_{6, 3} & x_{6, 4}\end{matrix} \\
\end{bmatrix}
\;\; \rightarrow \;\;
X^T =
\begin{bmatrix}
\boxed{\begin{matrix} x_{1, 1} \\ x_{1, 2} \\ x_{1, 3} \\ x_{1, 4}\end{matrix}} &
\begin{matrix} x_{2, 1} \\ x_{2, 2} \\ x_{2, 3} \\ x_{2, 4}\end{matrix} &
\begin{matrix} x_{3, 1} \\ x_{3, 2} \\ x_{3, 3} \\ x_{3, 4}\end{matrix} &
\begin{matrix} x_{4, 1} \\ x_{4, 2} \\ x_{4, 3} \\ x_{4, 4}\end{matrix} &
\begin{matrix} x_{5, 1} \\ x_{5, 2} \\ x_{5, 3} \\ x_{5, 4}\end{matrix} &
\begin{matrix} x_{6, 1} \\ x_{6, 2} \\ x_{6, 3} \\ x_{6, 4}\end{matrix} &
\end{bmatrix}
\end{align}
$$

### 브로드캐스팅(Broadcasting)

<figure>
    <img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">
</figure>

In [53]:
'''
브로드캐스팅은 자동으로 비어있는 배열을 채워서 연산을 수행하는 기능이다.
수학적으로 연산이 불가능한 벡터와 스칼라 간 연산이 가능해진다.
'''
vector = np.arange(3)
scalar = 2.
print_obj(vector, "vector")
print_obj(scalar, "scalar")
print_obj(vector+scalar, "vector+scalar")
print_obj(vector-scalar, "vector-scalar")
print_obj(vector*scalar, "vector*scalar")
print_obj(vector/scalar, "vector/scalar")

vector:
[0 1 2]

scalar:
2.0

vector+scalar:
[2. 3. 4.]

vector-scalar:
[-2. -1.  0.]

vector*scalar:
[0. 2. 4.]

vector/scalar:
[0.  0.5 1. ]



In [54]:
'''
브로드캐스팅을 통해 형태가 맞지 않은 두 행렬의 덧셈이 가능하다.
'''
mat1 = np.arange(6).reshape((3,2))
mat2 = np.arange(2).reshape(2) + 1
print_obj(mat1, "mat1")
print_obj(mat2, "mat2")
print_obj(mat1+mat2, "mat1+mat2")

mat3 = np.arange(12).reshape((2,3,2))
mat4= np.arange(6).reshape((3,2))
print_obj(mat3, "mat3")
print_obj(mat4, "mat4")
print_obj(mat3+mat4, "mat3+mat4")

mat1:
[[0 1]
 [2 3]
 [4 5]]

mat2:
[1 2]

mat1+mat2:
[[1 3]
 [3 5]
 [5 7]]

mat3:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

mat4:
[[0 1]
 [2 3]
 [4 5]]

mat3+mat4:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]

